module.exports = [
  {
    pName: "Malhar Tshirt(White)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtWhite.jpg",
    pDescription: "White Cotton Tshirt with Malhar 2021 logo on the front.",
    pCategory: "tshirt",
  },
  {
    pName: "Malhar Tshirt(Green)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtGreen.jpg",
    pDescription: "Green Cotton Tshirt with Malhar 2021 logo on the front.",
    pCategory: "tshirt",
  },
  {
    pName: "Malhar Tshirt(Gray)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtGray.jpg",
    pDescription: "Gray Cotton Tshirt with Malhar 2021 logo on the front.",
    pCategory: "tshirt",
  },

  {
    pName: "Xenith Tshirt(Gray)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtGrayX.jpg",
    pDescription: "Gray Cotton Tshirt with Xenith 2020 logo on the front.",
    pCategory: "tshirt",
  },
  {
    pName: "Xenith Tshirt(Black)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtBlack.jpg",
    pDescription: "Black Cotton Tshirt with Xenith 2020 logo on the front.",
    pCategory: "tshirt",
  },
  {
    pName: "Xenith Tshirt(White)",
    pPrice: 499,
    pImage: "/image/merch/hangTshirtWhiteX.jpg",
    pDescription: "White Cotton Tshirt with Xenith 2020 logo on the front.",
    pCategory: "tshirt",
  },
  {
    pName: "Malhar Cap(White)",
    pPrice: 199,
    pImage: "/image/merch/capWhite.jpg",
    pDescription: "White Cotton cap with Malhar 2021 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Malhar Cap(Gray)",
    pPrice: 199,
    pImage: "/image/merch/capGray.jpg",
    pDescription: "White Cotton cap with Malhar 2021 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Malhar Cap(Green)",
    pPrice: 199,
    pImage: "/image/merch/capGreen.jpg",
    pDescription: "Green Cotton cap with Malhar 2021 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Xenith cap(Black)",
    pPrice: 499,
    pImage: "/image/merch/capBlackX.jpg",
    pDescription: "Black Cotton cap with Xenith 2020 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Xenith cap(Gray)",
    pPrice: 199,
    pImage: "/image/merch/capGrayX.jpg",
    pDescription: "Gray Cotton cap with Xenith 2020 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Xenith cap(White)",
    pPrice: 199,
    pImage: "/image/merch/capWhiteX.jpg",
    pDescription: "White Cotton cap with Xenith 2020 logo on the front.",
    pCategory: "cap",
  },
  {
    pName: "Xenith mask(White)",
    pPrice: 299,
    pImage: "/image/merch/maskWhiteX.jpg",
    pDescription: "White Cotton mask with Xenith 2020 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Xenith mask(Black)",
    pPrice: 299,
    pImage: "/image/merch/maskBlackX.jpg",
    pDescription: "Black Cotton mask with Xenith 2020 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Xenith mask(Gray)",
    pPrice: 299,
    pImage: "/image/merch/maskGrayX.jpg",
    pDescription: "Gray Cotton mask with Xenith 2020 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Malhar mask(Green)",
    pPrice: 299,
    pImage: "/image/merch/maskGreen.jpg",
    pDescription: "Gray Cotton mask with Malhar 2021 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Malhar mask(Black|Gray)",
    pPrice: 299,
    pImage: "/image/merch/maskGrayBlack.jpg",
    pDescription: "Dual Tone Cotton mask with Malhar 2021 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Malhar mask(White)",
    pPrice: 299,
    pImage: "/image/merch/maskWhite.jpg",
    pDescription: "White Cotton mask with Xenith 2020 tagline on the side.",
    pCategory: "mask",
  },
  {
    pName: "Xenith Hoodie(Black)",
    pPrice: 799,
    pImage: "/image/merch/hoodieBlackX.jpg",
    pDescription: "Black Cotton hoodie with Xenith 2020 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Malhar Hoodie(Gray)",
    pPrice: 799,
    pImage: "/image/merch/hoodieGray.jpg",
    pDescription: "Gray Cotton hoodie with Malhar 2021 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Xenith Hoodie(Gray)",
    pPrice: 799,
    pImage: "/image/merch/hoodieGrayX.jpg",
    pDescription: "Gray Cotton hoodie with Xenith 2020 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Malhar Hoodie(Green)",
    pPrice: 799,
    pImage: "/image/merch/hoodieGreen.jpg",
    pDescription: "Green Cotton hoodie with Malhar 2021 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Malhar Hoodie(White)",
    pPrice: 799,
    pImage: "/image/merch/hoodieWhite.jpg",
    pDescription: "White Cotton hoodie with Malhar 2021 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Xenith Hoodie(White)",
    pPrice: 799,
    pImage: "/image/merch/hoodieWhiteX.jpg",
    pDescription: "White Cotton hoodie with Xenith 2020 logo on the front.",
    pCategory: "hoodie",
  },
  {
    pName: "Xenith Brooch",
    pPrice: 49,
    pImage: "/image/merch/badgeX.jpg",
    pDescription: "Brooch with Xenith 2020 logo on the front.",
    pCategory: "brooch",
  },
  {
    pName: "Malhar Brooch",
    pPrice: 49,
    pImage: "/image/merch/badge.jpg",
    pDescription: "Brooch with Malhar 2021 logo on the front.",
    pCategory: "brooch",
  },

];
